mod 'vrenetic/php5',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/php5'

mod 'vrenetic/nginx',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nginx'

mod 'vrenetic/mysql',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/mysql'

mod 'vrenetic/rsync',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/rsync'

mod 'vrenetic/helper',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/helper'
