mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'vrenetic/systemd',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/systemd'

mod 'vrenetic/monit',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/monit'

mod 'vrenetic/sudo',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/sudo'
