mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'vrenetic/rsyslog',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/rsyslog'

mod 'vrenetic/logrotate',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/logrotate'
