mod 'vrenetic/pulsar',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/pulsar'

mod 'vrenetic/nodejs',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'vrenetic/mongodb',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/mongodb'

mod 'vrenetic/logrotate',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'vrenetic/helper',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/helper'

mod 'vrenetic/bower',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/bower'

mod 'vrenetic/daemon',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/daemon'
