mod 'vrenetic/helper',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/helper'

mod 'vrenetic/apt',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/apt'

mod 'vrenetic/build',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/build'
