mod 'vrenetic/nodejs',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'vrenetic/logrotate',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'vrenetic/bipbip',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'vrenetic/nginx',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nginx'

mod 'vrenetic/mjr_convert',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/mjr_convert'

mod 'vrenetic/lame',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/lame'

mod 'vrenetic/fluentd',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/fluentd'
