mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'vrenetic/daemon',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/daemon'

mod 'vrenetic/dbus',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/dbus'
