mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'vrenetic/ssh',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ssh'

mod 'vrenetic/monit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/monit'

mod 'vrenetic/git',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/git'

mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'vrenetic/puppet',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/puppet'

mod 'vrenetic/postgresql',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/postgresql'

mod 'vrenetic/ufw',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/ufw'
