mod 'vrenetic/capistrano',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/capistrano'

mod 'vrenetic/git',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/git'

mod 'vrenetic/ruby',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ruby'

mod 'vrenetic/env',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/env'
