mod 'vrenetic/monit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/monit'

mod 'vrenetic/apt',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/apt'

mod 'vrenetic/ntp',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ntp'

mod 'vrenetic/ssh',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ssh'

mod 'vrenetic/unzip',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/unzip'

mod 'vrenetic/ufw',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/ufw'
