mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'vrenetic/kernel',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/kernel'

mod 'vrenetic/helper',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/helper'

mod 'vrenetic/monit',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/monit'
