mod 'vrenetic/janus',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/janus'

mod 'vrenetic/ffmpeg',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ffmpeg'
