mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'vrenetic/lightdm',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/lightdm'

mod 'vrenetic/accountsservice',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/accountsservice'

mod 'vrenetic/xpra',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/xpra'
