mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'vrenetic/apt',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/apt'

mod 'vrenetic/ntp',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ntp'

mod 'vrenetic/bipbip',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'vrenetic/logrotate',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'vrenetic/daemon',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/daemon'
