mod 'vrenetic/daemon',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/daemon'

mod 'vrenetic/bipbip',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'vrenetic/logrotate',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'vrenetic/build',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/build'

mod 'vrenetic/git',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/git'

mod 'vrenetic/helper',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/helper'

mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'vrenetic/fluentd',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/fluentd'

mod 'vrenetic/needrestart',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/needrestart'
