# Circular dependency not supported
#
#mod 'vrenetic/bipbip',
#  :git => 'git@github.com:vrenetic/puppet-packages.git',
#  :path => 'modules/bipbip'
#
#mod 'vrenetic/postfix',
#   :git => 'git@github.com:vrenetic/puppet-packages.git',
#   :path => 'modules/postfix'

mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'
