mod 'vrenetic/apt',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/apt'

mod 'vrenetic/logrotate',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'vrenetic/daemon',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/daemon'

mod 'vrenetic/ufw',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/ufw'
