mod 'vrenetic/apt',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/apt'

mod 'vrenetic/build',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/build'

mod 'vrenetic/helper',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/helper'

mod 'vrenetic/gearman',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/gearman'

mod 'vrenetic/monit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/monit'

mod 'vrenetic/bipbip',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'vrenetic/logrotate',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'vrenetic/git',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/git'

mod 'vrenetic/openssl',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/openssl'
