mod 'vrenetic/ca_certificates',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ca_certificates'

mod 'vrenetic/monit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/monit'

mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'
