mod 'vrenetic/apt',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/apt'

mod 'vrenetic/java',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/java'

mod 'vrenetic/helper',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/helper'

mod 'vrenetic/monit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/monit'
