mod 'vrenetic/nginx',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nginx'

mod 'vrenetic/daemon',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/daemon'

mod 'vrenetic/helper',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/helper'

mod 'puppetlabs/stdlib',
    :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'vrenetic/ufw',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/ufw'

mod 'vrenetic/unzip',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/unzip'

mod 'vrenetic/apt',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/apt'
