mod 'vrenetic/sysctl',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/sysctl'

mod 'vrenetic/bipbip',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'vrenetic/database',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/database'

mod 'vrenetic/logrotate',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'vrenetic/daemon',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/daemon'
