mod 'vrenetic/nodejs',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'vrenetic/monit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/monit'

mod 'vrenetic/daemon',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/daemon'
