mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'vrenetic/composer',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/composer'

mod 'vrenetic/php5',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/php5'

mod 'vrenetic/phpunit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/phpunit'

mod 'vrenetic/uglify',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/uglify'

mod 'vrenetic/browserify',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/browserify'

mod 'vrenetic/autoprefixer',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/autoprefixer'

mod 'vrenetic/foreman',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/foreman'

mod 'vrenetic/foreman_systemd',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/foreman_systemd'

mod 'vrenetic/mysql',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/mysql'

mod 'vrenetic/redis',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/redis'

mod 'vrenetic/memcached',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/memcached'

mod 'vrenetic/elasticsearch',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/elasticsearch'

mod 'vrenetic/gearman',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/gearman'

mod 'vrenetic/socket_redis',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/socket_redis'

mod 'vrenetic/nginx',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nginx'

mod 'vrenetic/bipbip',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'vrenetic/mongodb',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/mongodb'

mod 'vrenetic/cm_janus',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/cm_janus'

mod 'vrenetic/janus',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/janus'

mod 'vrenetic/ufw',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ufw'

mod 'vrenetic/phantomjs',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/phantomjs'

mod 'vrenetic/systemd',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/systemd'
