mod 'vrenetic/composer',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/composer'

mod 'vrenetic/git',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/git'

mod 'vrenetic/nginx',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nginx'

mod 'vrenetic/ufw',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/ufw'
