mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'vrenetic/ssh',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ssh'

mod 'vrenetic/helper',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/helper'

mod 'vrenetic/git',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/git'

mod 'vrenetic/ruby',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ruby'

mod 'vrenetic/librarian_puppet',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/librarian_puppet'

mod 'vrenetic/rsync',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/rsync'

mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'vrenetic/daemon',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/daemon'

mod 'vrenetic/bipbip',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/bipbip'
