mod 'vrenetic/build',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/build'

mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'
