mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'vrenetic/fluentd',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/fluentd'
