mod 'vrenetic/monit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/monit'

mod 'vrenetic/bipbip',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'vrenetic/sysctl',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/sysctl'

mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

