mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'vrenetic/apt',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/apt'

mod 'vrenetic/monit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/monit'

mod 'vrenetic/helper',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/helper'

mod 'vrenetic/python',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/python'

mod 'vrenetic/unzip',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/unzip'
