mod 'vrenetic/augeas',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/augeas'

mod 'vrenetic/sysctl',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/sysctl'

mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'
