mod 'vrenetic/apt',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/apt'

mod 'vrenetic/systemd',
    :git => 'git@github.com:vrenetic/puppet-packages.git',
    :path => 'modules/systemd'
