mod 'vrenetic/apt',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/apt'

mod 'vrenetic/helper',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/helper'

mod 'vrenetic/java',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/java'
