mod 'vrenetic/apt',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/apt'

mod 'vrenetic/build',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/build'

mod 'vrenetic/cgi_fcgi',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/cgi_fcgi'

mod 'vrenetic/ruby',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ruby'

mod 'vrenetic/monit',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/monit'

mod 'vrenetic/logrotate',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/logrotate'
