mod 'vrenetic/cm',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/cm'

mod 'vrenetic/composer',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/composer'

mod 'vrenetic/gdisk',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/gdisk'
