mod 'vrenetic/ruby',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/ruby'

mod 'vrenetic/daemon',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/daemon'

mod 'vrenetic/logrotate',
   :git => 'git@github.com:vrenetic/puppet-packages.git',
   :path => 'modules/logrotate'
