mod 'vrenetic/janus',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/janus'

mod 'vrenetic/janus_cluster_manager',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/janus_cluster_manager'
