mod 'vrenetic/rdiff_backup',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/rdiff_backup'

mod 'vrenetic/ssh',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/ssh'
