mod 'vrenetic/nodejs',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'vrenetic/daemon',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/daemon'

mod 'vrenetic/nginx',
  :git => 'git@github.com:vrenetic/puppet-packages.git',
  :path => 'modules/nginx'
